### ISSUE TITLE
Report for Safari

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#21]
It would include:
* bookmarks "/Library/Safari/Bookmarks.db"
* history "/Library/Safari/History.db"
* browser state "/Library/Safari/BrowserState.db"
* something else?

We would do it, but we are wondering how should we create the report?

I think it would be too much to add report for each database. The report list might get a bit too long. Maybe there could be an extra flag for sub-report? Or there are several tables/json objects coming out from one report?

What do you think @richinfante ?

**Comment by richinfante** [comment]
Hmm, for now it would probably be best to keep them in separate reports to allow for clarity into what each individual one does. There's already some support for web history in the existing `webhistory` report. The `cookies` report also follows this pattern already.

It’s a good point that the list of these reports will start to grow quickly with lots of individual reports so what I’m thinking is for the future I’ll build something like this to allow for a bit more structure:
- Add the ability to define groups of reports such as `safari` which would contain the `webhistory`, `browserstate`, etc.., reports. If `safari` is selected, it'd run them in a similar manner to the `all` report currently.
- Users could still specify a single sub-report and it'd still work as it currently does.
    - In the event that there's naming clashes between reports, they individually could be referenced like so: `safari.webhistory` or `safari.browserstate`
- The reports listing would hierarchically display them so it's a bit more readable than just a huge list.
- JSON reports can be joined and nested hierarchically based on their group, if the `--join-reports` flag is set.
- This'll still allow for `csv` and `table` outputs to function as they did before, since they don't support nesting in the same way as json.

I’ll experiment with this and see if I can get anything useful working.

Additionally there's a safari preferences plist file under the `AppDomain-com.apple.mobilesafari: Library/Preferences/com.apple.mobilesafari.plist`, which contains recent web searches (at least on iOS 11), which you might want to take a look at. I’ll probably end up building a report for it at some point.

**Comment by timotoots** [comment]
Hey Rich, how is this going? We are planning to implement some sub-report for apps. What's the best way to code it at this point, so it's easy to upgrade to later to sub-report functionality. @aguerere

**Comment by richinfante** [comment]
If they're implemented to the current conventions it shouldn't be too difficult to upgrade. Perhaps if they're named in a format like: `safari_bookmarks`, (`{{appname}}_{{reportname}}`), It'll be easier when I'm upgrading the reports to work with the sub-report function so I know how they should be grouped.

I'm hoping to have the sub-report functionality done within the next few days.
