### ISSUE TITLE
Partial backups

### ISSUE THREAD

**Issue by aguerere** [richinfante/iphonebackuptools#31]
Hi @richinfante 

If an iTunes backup is cancelled, some data may still be available for iphonebackuptools.
Currently, it looks like it always try to read the Manifest file and Info.plist . If either of them are not found, the process stops with errors.

Many of the available reports have known file hashes, so those checks could be skipped if the Manifest and Info files are not found and still try to access the file(s) the report needs and provide results if any are found.

Do you think we can fix/enable this for partial backups? We can do a pull request with the changes.
Cheers

**Comment by richinfante** [comment]
I don't think it should be too difficult, there isn't any direct dependency on the manifests other than version checking and in the backup list. This is similar to something that was brought up in #14 with database auto-discovery and I think it's probably a valuable feature to have.

In order to make this happen we'd need to make reports not rely on version checking to detect features, and instead check if the specific targeted files exist and are not corrupted. I'm currently working on the report enhancements mentioned in #21, so I'll explore adding this in addition to what I'm currently working on.

**Comment by timotoots** [comment]
Did this feature get implemented? I have tested and it does not do reports on partial backups.
